name: Download from aws

on: 
  workflow_dispatch:
    inputs:
      runId:
        description: 'RunId'
        required: true
        default: ''

jobs:
  runscript:
    name: Download test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true      

      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/MaximMatveevOneUp/TestCache/actions/runs/${{ github.event.inputs.runId }}
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"

      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "${{ steps.downloadfile.outputs.filename }}" >> $GITHUB_STEP_SUMMARY 
          echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
          

  