name: Build Android Develop test (Self-Hosted)

on:
  push:
  workflow_dispatch:
    inputs:
      standName:
        description: 'Stand by default'
        required: true
        default: 'CST1'
        type: choice
        options:
          - RELEASE
          - STAGE
          - SST1
          - CST1
          - QST1
          - PST1
      developmentBuild:
        description: 'Development Build'
        required: true
        default: true
        type: boolean
      allowDebugging:
        description: 'Allow Debugging'
        required: true
        default: false
        type: boolean
      buildWithDeepProfilingSupport:
        description: 'Deep Profiling Support'
        required: true
        default: false
        type: boolean
      restoreCache:
        description: 'Restore Cache'
        required: false
        default: true
        type: boolean
      saveCache:
        description: 'Save Cache'
        required: false
        default: true
        type: boolean
      androidAppBundle:
        description: 'Android AppBundle'
        required: true
        default: false
        type: boolean
      exportProject:
        description: 'Export Android Studio Project'
        required: true
        default: false
        type: boolean
      buildSettingsPreset:
        type: choice
        description: 'BuildSettings preset name'      
        options: 
        - Develop
        - Release
        default: Develop       

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:          
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.7.0

      - uses: actions/checkout@v2

      - name: Set values
        id: values
        run: |
          echo "buildWithDeepProfilingSupport=${{ github.event.inputs.buildWithDeepProfilingSupport || false }}" >> $GITHUB_ENV
          echo "restoreCache=${{ github.event.inputs.restoreCache || false}}" >> $GITHUB_ENV
          echo "saveCache=${{ github.event.inputs.saveCache || true}}" >> $GITHUB_ENV
          echo "standName=${{ github.event.inputs.standName || 'CST1'}}" >> $GITHUB_ENV
          echo "androidExportType=${{ github.event.inputs.androidExportType || 'androidPackage'}}" >> $GITHUB_ENV
          echo "developmentBuild=${{ github.event.inputs.developmentBuild || true }}" >> $GITHUB_ENV
          echo "allowDebugging=${{ github.event.inputs.allowDebugging || false }}" >> $GITHUB_ENV
          echo "CACHE_FOLDER_PATH=$SHARED_BUILD_FOLDER_PATH/cache/android/"  >> $GITHUB_ENV        

      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY      
          echo "developmentBuild: ${{ env.developmentBuild }}" >> $GITHUB_STEP_SUMMARY
          echo "saveCache: ${{ env.saveCache }}" >> $GITHUB_STEP_SUMMARY       
          echo "standName=${{ env.standName }}" >> $GITHUB_STEP_SUMMARY
          echo "androidExportType=${{ env.androidExportType }}"  >> $GITHUB_STEP_SUMMARY
          echo "allowDebugging: ${{ env.allowDebugging }}" >> $GITHUB_STEP_SUMMARY          

      - name: Save state
        id: build_errors
        uses: MaximMatveevOneUp/errors_from_logs@main
        with:
          logFile: cleanedLogFile.txt

      - name: Set output
        run: |
          echo "Errors: ${{ steps.build_errors.outputs.result }}" >> $GITHUB_STEP_SUMMARY

      - name: Generate build errors summary
        run: |
          messgae='grep "error cs" cleanedLogFile.txt'
          echo "messgae=${messgae}"

      - name: Set output
        run: echo "Branch=${{ env.CI_REF_NAME }}" >> $GITHUB_OUTPUT