name: Build
on:
  workflow_dispatch:
    inputs:
      runId:
        description: 'RunId'
        required: true
        default: ''
      upload:
        description: 'Upload'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: my-event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "runId": "${{ github.event.inputs.runId }}", "upload":  "runId": "${{ github.event.inputs.upload }}"}'

    - name: Generate summary
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY 
        echo "Branch: ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY