name: Copy license
on:
  workflow_dispatch:
    inputs:
      firebaseUpload:
        description: 'Upload build to Firebase'
        required: true
        default: true
        type: boolean        

jobs:
  copyfile:
    name: Copy license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set values
      id: values
      run: |
        echo "firebaseUpload=${{ github.event.inputs.firebaseUpload || false }}" >> $GITHUB_ENV
        
  firebaseUpload:
    if: github.event.inputs.firebaseUpload
    needs: copyfile
    name: Upload to firebase    
    runs-on: ubuntu-latest
    steps:
      - name: Set values
        id: values
        run: |
          echo "firebaseUpload=${{ github.event.inputs.firebaseUpload || false }}" >> $GITHUB_ENV        
