name: Copy license
on:
  workflow_dispatch:
    inputs:
      source_path:
        description: 'Path to source file'
        required: true
        default: 'test_fule.txt'
      dest_path:
        description: 'Path to dest file'
        required: true
        default: 'test_fule.txt'

jobs:
  copyfile:
    name: Copy license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        source: ${{ github.event.inputs.path }}
        target: "test-a.txt"