name: Copy license
on:
  workflow_dispatch:
    inputs:
      firebaseUpload:
        description: 'Upload build to Firebase'
        required: true
        default: true
        type: boolean        

jobs:
  copyfile:
    name: Copy license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set values
      id: values
      run: |
        echo "firebaseUpload=${{ github.event.inputs.firebaseUpload || false }}" >> $GITHUB_ENV
        ls /github/workspace

    - name: Install and upload
      if: env.firebaseUpload == 'true'
      run: |
        curl -sL https://firebase.tools | bash

    - name: Updalod Symobls to Firebase Crashlytics
      if: env.firebaseUpload == 'true'
      uses: MaximMatveevOneUp/Firebase-Crashlytics-Github@main
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
        file: '${{ env.symbolsFilePath }}' 
