name: Copy license
on:
  workflow_dispatch:
    inputs:
      firebaseUpload:
        description: 'Upload build to Firebase'
        required: true
        default: true
        type: boolean        

jobs:
  copyfile:
    name: Copy license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install and upload
      run: |
        symbolsFile=$(find . -type f -name '*.symbols.zip')
        export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}      
        curl -sL https://firebase.tools | bash
        firebase crashlytics:symbols:upload --app=${{secrets.FIREBASE_APP_ID}} $symbolsFile        
        
