name: Copy license
on:
  workflow_dispatch:
    inputs:
      firebaseUpload:
        description: 'Upload build to Firebase'
        required: true
        default: true
        type: boolean        

jobs:
  copyfile:
    name: Copy license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Firebase
      run: |        
        sudo apt-get install openjdk-11-jdk
        curl -sL https://firebase.tools | bash
        symbolsFile='test'
        export GOOGLE_APPLICATION_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}'
        firebase crashlytics:symbols:upload --app=${{secrets.FIREBASE_APP_ID}} $symbolsFile           
        
    - name: Upload
      run: |
        symbolsFile=$(find . -type f -name '*.symbols.zip')
        export GOOGLE_APPLICATION_CREDENTIALS='${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}'
        firebase crashlytics:symbols:upload --app=${{secrets.FIREBASE_APP_ID}} $symbolsFile         
