name: Deploy Appcenter

on: 
  workflow_dispatch:
    inputs:
      appcenterGroup:
        description: 'Appcenter group'
        required: true
        default: 'gg_team'
        type: choice
        options:
          - gg_team
jobs:
  runscript:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: snow-actions/qrcode@v1.0.0
        with:
          text: https://appcenter.ms/orgs/OneUp-Games/apps/GG/
          path: .github/qr_codes/${{ github.run_id }}.png

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: .github/qr_codes
          clean: false

      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="link address"><img src="https://maximmatveevoneup.github.io/TestCache/${{ github.run_id }}.png"></a>" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="https://appcenter.ms/orgs/OneUp-Games/apps/GG/">Download url</a>" >> $GITHUB_STEP_SUMMARY 

          