name: Deploy Appcenter

on: 
  workflow_dispatch:
    inputs:
      appcenterGroup:
        description: 'Appcenter group'
        required: true
        default: 'gg_team'
        type: choice
        options:
          - gg_team
jobs:
  runscript:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>" >> $GITHUB_STEP_SUMMARY 