name: Deploy Appcenter

on: 
  workflow_dispatch:
    inputs:
      appcenterGroup:
        description: 'Appcenter group'
        required: true
        default: 'gg_team'
        type: choice
        options:
          - gg_team
jobs:
  runscript:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: upload artefact to App Center
        id: upload_appcenter
        uses: MaximMatveevOneUp/AppCenter-Github-Action@vmaster
        with:
          appName: OneUp-Games/GG
          token: ${{secrets.APP_CENTER_TOKEN_ANDROID}}
          group: ${{ github.event.inputs.appcenterGroup }}
          file: /Users/maxim.m/Builds/Client/gg1.apk
          notifyTesters: true
          debug: false

      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "https://install.appcenter.ms/orgs/OneUp-Games/apps/GG/releases/${{ steps.upload_appcenter.outputs.releaseId }}"" >> $GITHUB_STEP_SUMMARY 