name: Deploy Appcenter

on: 
  workflow_dispatch:
    inputs:
      appcenterGroup:
        description: 'Appcenter group'
        required: true
        default: 'gg_team'
        type: choice
        options:
          - gg_team
jobs:
  runscript:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}          
    steps:
      - uses: actions/checkout@v2

      - uses: snow-actions/qrcode@v1.0.0
        with:
          text: https://appcenter.ms/orgs/OneUp-Games/apps/GG/
          path: .github/qr_codes/${{ github.run_id }}.png

      - uses: actions/upload-artifact@v2
        with:
          name: "${{ github.run_id }}.png"
          path: ".github/qr_codes/${{ github.run_id }}.png"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ".github/qr_codes"

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1


      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "Scan this QR code to download the release" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="https://appcenter.ms/orgs/OneUp-Games/apps/GG/"><img src="https://maximmatveevoneup.github.io/TestCache/${{ github.run_id }}.png"></a>" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="https://appcenter.ms/orgs/OneUp-Games/apps/GG/">Download url</a>" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<table><tr><td>${{ steps.qrcode.output.text }}</td></tr></table>" >> $GITHUB_STEP_SUMMARY 

          echo "${{ steps.qrcode.output.data }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.qrcode.output.text }}" >> $GITHUB_STEP_SUMMARY

          