name: Deploy Appcenter

on: 
  workflow_dispatch:
    inputs:
      appcenterGroup:
        description: 'Appcenter group'
        required: true
        default: 'gg_team'
        type: choice
        options:
          - gg_team
jobs:
  runscript:
    name: Upload to AppCenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate QR Code
        id: qrcode
        uses: hammadj/qr-code-generator@master
        with:
          # Example using text outputted from another step action
          content: "https://appcenter.ms/orgs/OneUp-Games/apps/GG/"

      - uses: snow-actions/qrcode@v1.0.0
        with:
          text: https://appcenter.ms/orgs/OneUp-Games/apps/GG/
          path: .github/qr_codes/${{ github.run_id }}.png

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: .github/qr_codes
          commit-message: Qr code for ${{ github.run_id }} 
          clean: false

      - name: Generate summary
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "Scan this QR code to download the release" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="link address"><img src="https://maximmatveevoneup.github.io/TestCache/${{ github.run_id }}.png"></a>" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<a href="https://appcenter.ms/orgs/OneUp-Games/apps/GG/">Download url</a>" >> $GITHUB_STEP_SUMMARY 
          echo "" >> $GITHUB_STEP_SUMMARY 
          echo "<table><tr><td>${{ steps.qrcode.output.text }}</td></tr></table>" >> $GITHUB_STEP_SUMMARY 

          echo "${{ steps.qrcode.output.data }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.qrcode.output.text }}" >> $GITHUB_STEP_SUMMARY

          