name: Triggered After Build
on:
  repository_dispatch:
    types: [my-event]


jobs:
  build:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Generate summary
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY 
        echo "Branch: ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.workflow_run.conclusion }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.workflow_run.id }}" >> $GITHUB_STEP_SUMMARY        
        echo "${{ github.event.workflow_run.head_sha }}" >> $GITHUB_STEP_SUMMARY                
        echo "${{ github.event.workflow_run.head_branch}}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.workflow_run.event}}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.inputs.upload }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.client_payload.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.client_payload.runId }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ github.event.client_payload.upload }}" >> $GITHUB_STEP_SUMMARY
