name: Triggered After Build
on:
  workflow_run:
    workflows:
      - Build
    branches:
      - develop
    types:
      - completed


jobs:
  build:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Generate summary
      run: |
        echo "" >> $GITHUB_STEP_SUMMARY 
        echo "Branch: ${GITHUB_REF_NAME}" >> $GITHUB_STEP_SUMMARY